### PR TITLE
to_hash not returning hash with changes, but origin hash

### PR DESCRIPTION
**Pull request by danielhusar**
Hey, is this intended behaviour ?

### CODE REVIEW

**Comment by jsuchal** [comment]
@danielhusar probably not. @vinh0604 thoughts?

**Comment by vinh0604** [comment]
@jsuchal @danielhusar It seems like a bug of `to_hash` implementation, it should return the updated hash instead of the original hash. I'll submit the fix soon.

**Comment by danielhusar** [comment]
Nice, I haven't really tested it, but isn't each affected by this as well ? As it uses `table_with_original_keys`

**Comment by vinh0604** [comment]
I'm not sure about `each`, but I think it should also use `@table` instead of `@table_with_original_keys`. Maybe @jsuchal could clarify this.

**Comment by danielhusar** [comment]
Closing for inactivity.

**Pull request closed without merging**
